config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :projects do
    resources :tasks
  end

  get "about"=>"welcome#about", as: :about
  get "terms"=>"welcome#terms", as: :terms
  get '/faqs' => 'faqs#index', as: :faq

  get "/signup" => "registrations#new", as: :registrations
  post "/signup" => "registrations#create"

  get "/signin" => "authentication#new", as: :sign_in
  post "/signin" => "authentication#create"

  get '/sign-out' => 'authentication#destroy', as: :signout

  root 'welcome#home', as: :root

end

app/models/faq.rb
class Faq < ActiveRecord::Base

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :name, presence: true
  has_many :tasks

end

app/models/registration.rb
class Registration < ActiveRecord::Base

  has_secure_password

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/task.rb
class Task < ActiveRecord::Base

  validates :description, presence: true
  validate :due_date_cannot_be_in_the_past, on: :create

  def due_date_cannot_be_in_the_past
    if due_date && due_date < Date.today
      errors.add(:due_date, "can't be in the past")
    end
  end


  belongs_to :project

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  has_secure_password

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  require 'csv'

  def current_user
    User.find_by(id: session[:user_id])
  end

  helper_method :current_user

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def create
    user=User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      @sign_in_error = "Username / password combination is invalid"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController

  def index
    @faqs=Faq.all
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects=Project.all
  end

  def new
    @project=Project.new
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @project=Project.find(params[:id])
  end

  def edit
    @project=Project.find(params[:id])
  end

  def destroy
    @project=Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update
    @project = Project.find(params[:id])
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  before_action do
    @project = Project.find(params[:project_id])
  end

  # GET /tasks
  # GET /tasks.json
  def index
    if params[:type]=="incomplete"
      @tasks=@project.task.where({complete: false})
    else
      @tasks = @project.tasks
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @project.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_task_path(@project, @task), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_task_path(@project, @task), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :complete, :due_date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users=User.all
  end

  def new
    @user=User.new
  end

  def show
    @user=User.find(params[:id])
  end

  def destroy
    @user=User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end



  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController<ApplicationController
  def home
    @quotes_array=[["\"Failure is not an option. Everyone has to Succeed\"","Arnold Schwarzenegger"],
      ["\"Your time is limited so don't waste it living someone elses life\"","Steve Jobs",],
      ["\"Better ingredients, better pizza\"","Papa Johns"],]
  end

  def about

  end

  def terms

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<div class="well col-md-4 col-md-offset-4">

<h1>Sign in to gCamp!</h1>

<%= form_tag signin_path do |f| %>

<% if @sign_in_error %>
<p>
  <font color="red"><%= @sign_in_error %></font>
</p>
<% end %>

<div>
  <%= label_tag :email %>
</div>
<div class>
  <%= email_field_tag :email %>
</div>

<div>
  <%= label_tag :password %>
</div>
<div>
  <%= password_field_tag :password %>
</div>

<div>
  <%= submit_tag "Sign in", class: "btn btn-primary" %>
</div>

<% end %>
</div>

app/views/faqs/index.html.erb
<h1>Frequently Asked Questions</h1>

<div>

  <% @faqs.each do |faq| %>
  <p><b><%= faq.question %></b></p>
  <p><%= faq.answer %></p>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<% if notice %>
<center id="notice" class="alert alert-success" role="alert"> <font color="green"> <%= notice %> </font></center>
<% end %>

  <div>
    <head>
      <title>GCamp</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
    </head>


    <body data-no-turbolink class="container">
      <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
          <div class="navbar-header">
            <%= link_to "gCamp", root_path, class: "navbar-brand" %>
          </div>
            <ul class="navbar-right">
              <% if current_user %>
                <%= link_to current_user.full_name, user_path(current_user[:id]) %>
                |
                <%= link_to "Sign Out", signout_path %>
              <% else %>
                <%= link_to "Sign Up", registrations_path %>
                |
                <%= link_to "Sign In", signin_path %>
              <% end %>
            </ul>
          </div>
      </nav>



    <div>
      <%= yield %>
    </div>

    <div>
      <footer class="navbar navbar-fixed-bottom container">
      <hr>
        <%= link_to "About", about_path %> |
        <%= link_to "Terms", terms_path %> |
        <%= link_to "FAQ", faq_path %> |
        <%= link_to "Users", users_path %> |
        <%= link_to "Projects", projects_path %>
      </footer>
    </div>

  </body>


  </div>
</html>

app/views/projects/edit.html.erb
<h1 class="page-header"> Edit Project </h1>

<%= form_for(@project, html: {class: "form-horizontal"}) do |f| %>
<% if @project.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
  <h2><%= pluralize(@project.errors.count, "error") %> prohibited this task from being saved:</h2>

  <ul>
    <% @project.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>

<% end %>

<div class="form-group">
  <%= f.label :name, class: "col-sm-1 control-label" %>
  <div class="col-sm-5">
    <%= f.text_field :name, class:"form-control" %>
  </div>
</div>

<div class="actions" >
  <%= f.submit :class => "btn btn-primary col-sm-offset-1"%>
  <%= link_to 'Cancel', projects_path, :class => "btn btn-default" %>
</div>

<% end %>

app/views/projects/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'New Project', new_project_path, class: "btn btn-info" %>
  </div>
  <h1>Projects</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tasks</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, project %></td>
      <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>Create Project</h1>
</div>

<%= form_for(@project, html: {class: "form-horizontal"}) do |f| %>
<% if @project.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
  <h2><%= pluralize(@project.errors.count, "error") %> prohibited this task from being saved:</h2>

  <ul>
    <% @project.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>

<% end %>

<div class="form-group">
  <%= f.label :name, class: "col-sm-1" %>
  <div class="col-sm-5">
    <%= f.text_field :name, class:"form-control" %>
  </div>
</div>

<div class="actions" >
  <%= f.submit :class => "btn btn-primary col-sm-offset-1"%>
  <%= link_to 'Cancel', projects_path, :class => "btn btn-default" %>
</div>

<% end %>

app/views/projects/show.html.erb
<h1> <%= @project.name %> </h1>

<div class="pull-right">
  <%= link_to "edit", edit_project_path, class: "btn btn-info" %>
  <%= link_to "delete", project_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>

app/views/tasks/_form.html.erb
<%= form_for( @project, @task, html: {class: "form-horizontal"}) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-1 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :description, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :due_date, class: "col-sm-1 control-label" %>
    <div class="col-sm-2">
      <%= f.date_field :due_date, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-2 col-sm-offset-1">
      <%= f.check_box :complete  %>
      <%= f.label :complete %>
    </div>
  </div>

  <div class="actions" >
    <%= f.submit :class => "btn btn-primary col-sm-offset-1"%>
    <%= link_to 'Cancel', project_tasks_path(@project), :class => "btn btn-default" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>


<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "All", type: "all"%> |
    <%= link_to "Incomplete", type: "incomplete"%>
    <%= link_to 'New Task', new_project_task_path(@project), class: "btn btn-info" %>
  </div>
  <h1>Tasks</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Description</th>
      <th>Completed</th>
      <th>Due</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.complete %></td>
        <td><%= task.due_date %></td>
        <td class="pull-right">
          <%= link_to 'Show', project_task_path(@project, task), class: "btn btn-success" %>
          <%= link_to 'Edit', edit_project_task_path(@project, task), class: "btn btn-info" %>
          <%= link_to 'Delete', project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for([@project,@task], html: {class: "form-horizontal"}) do |f| %>
  <% if @task.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

    <ul>
      <% @task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-1 control-label" %>
    <div class="col-sm-5">
      <%= f.text_field :description, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :due_date, class: "col-sm-1 control-label" %>
    <div class="col-sm-2">
      <%= f.date_field :due_date, class:"form-control" %>
    </div>
  </div>

  <div class="actions" >
    <%= f.submit :class => "btn btn-primary col-sm-offset-1"%>
    <%= link_to 'Cancel', project_tasks_path(@project), :class => "btn btn-default" %>
  </div>
<% end %>

app/views/tasks/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.complete %>
</p>

<p>
  <strong>Due Date:</strong>
  <%= @task.due_date %>
</p>



<%= link_to 'Edit', edit_project_task_path(@project, @task) %> |
<%= link_to 'Back', project_tasks_path(@project) %>

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this task from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>

<% end %>

<div class="form-group">
    <%= f.label :first_name, class: "col-xs-2 control-label" %>
  <div class="col-sm-5">
    <%= f.text_field :first_name, class:"form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :last_name, class: "col-sm-2 control-label" %>
  <div class="col-sm-5">
    <%= f.text_field :last_name, class:"form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :email, class: "col-sm-2 control-label" %>
  <div class="col-sm-5">
    <%= f.email_field :email, class:"form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :password, class: "col-sm-2 control-label" %>
  <div class="col-sm-5">
    <%= f.email_field :password, class:"form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
  <div class="col-sm-5">
    <%= f.email_field :password_confirmation, class:"form-control" %>
  </div>
</div>

<div class="actions col-sm-offset-2" >
  <%= f.submit :class => "btn btn-primary"%>
  <%= link_to 'Cancel', users_path, :class => "btn btn-default" %>
</div>

<br>


<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<div class="well form-group col-sm-5 col-sm-offset-2">
  <%= link_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger col-sm-offset-4 col-sm-4" %>
</div>

app/views/users/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'New User', new_user_path, class: "btn btn-info" %>
  </div>
  <h1>Users</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= link_to "#{user.first_name} #{user.last_name}", user %></td>
      <td><%= mail_to user.email %></td>
      <td class="pull-right">
        <%= link_to 'edit', edit_user_path(user) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<div class="page-header">
  <h1>New User</h1>
</div>


<%= render 'form' %>

app/views/users/show.html.erb
<div class="pull-right">
  <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-info" %>
</div>

<h1><%= "#{@user.first_name} #{@user.last_name}" %></h1>

<br>


<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>

</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= mail_to @user.email %>
</p>

app/views/welcome/about.html.erb
<h1>About</h1>
<div class="row">
  <div><%= image_tag "pic4.jpg", class: "col-md-4" %></div>
      <p>We are dedicated to the makers, the creators, the risk-takers.  We wake up in the middle of the night and furiously write down ideas about how to make life better.</p>
      <p>When we're not hard at work, we're hard at play - we're the loud ones in the bar, and we're always the ones shutting the place down.  Human communication and collaboration is what drives us, and it infuses every feature of gCamp.</p>
  </div>

app/views/welcome/faq.html.erb
<h1>Frequently Asked Questions</h1>

<div>

  <% @faq_array.each do |faq| %>
    <p><b><%= faq[0] %></b></p>
    <p><%= "#{faq[1]}" %></p>
  <% end %>

</div>

app/views/welcome/home.html.erb
<div class="jumbotron">
  <h1>gCamp</h1>
  <p>Your life, organized.</p>
</div>

  <div  class="row col-sm-height">
    <div  class="col-md-4">
      <div> <%= image_tag "pic2-1.jpg", class:"img-responsive", alt:"Responsive image"%> </div>
      <div style="margin-top: 20px" class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Tasks</h3>
        </div>
        <div class="panel-body" style="height: 200px">
            Grouped by projects and lists.  Just the way you like'em
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div> <%= image_tag "pic2-2.jpg", class:"img-responsive", alt:"Responsive image"%> </div>
      <div style="margin-top: 20px" class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Documents</h3>
        </div>
        <div class="panel-body" style="height: 200px">
          <ul>
            <li>Upload</li>
            <li>Comment</li>
            <li>Revise</li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div> <%= image_tag "pic2-3.jpg", class:"img-responsive", alt:"Responsive image"%> </div>
      <div style="margin-top: 20px" class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">Comments</h3>
        </div>
        <div class="panel-body" style="height: 200px">
            <ul>
              <li>Comment on tasks and documents</li>
              <li>Get email notifications</li>
            </ul>
        </div>
      </div>
    </div>
  </div>


  <div>
    <% @quotes_array.each do |quote| %>
        <%= quote[0] %>
      <p><font color="grey"><i> <%= "- #{quote[1]}" %> </i></font></p>
    <% end %>
  </div>

app/views/welcome/terms.html.erb
<div>
<h1> Terms <h1>
</div>

<div>
  <p> gCamp is not responsible for anything, unless it is positive. </p>
  <p> You may not take us to court, for anything ever.</p>
</div>